vich_uploader:
    db_driver: orm

    mappings:
        item_image:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /images/items
            upload_destination: '%kernel.project_dir%/public/images/items'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true